[build]
# Define a linguagem e a versão do SDK. Ajuste conforme a versão que você está usando.
builder = "flutter"
flutter_sdk_version = "3.0.0"

[[build.packages]]
# Dependências do sistema necessárias podem ser adicionadas aqui. Por exemplo, se você precisa de ferramentas específicas do SO ou bibliotecas.

[[build.commands]]
# Comandos de build personalizados podem ser listados aqui. Para um projeto Flutter, normalmente começaria com `flutter pub get`.
pre = "flutter pub get"
build = "flutter build web"



